USE MALL;
START TRANSACTION;
INSERT INTO ORDERS(M_ID, P_ID, O_QTY, O_DATE) 
VALUES(1, 101, 2, NOW());
SELECT * FROM ORDERS;
UPDATE PRODUCT SET P_STOCK = P_STOCK - 2 WHERE P_ID = "101";
SELECT * FROM PRODUCT;
UPDATE MEMBER SET M_POINT = M_POINT + 100 WHERE M_ID = "1";
SELECT * FROM MEMBER;
COMMIT;

# 1번 회원이 주문한 상품명을 조회(JOIN 이용)
SELECT M_ID, P_NAME FROM ORDERS
JOIN PRODUCT USING(P_ID)
WHERE M_ID = '1';


