spring.application.name=post

spring.thymeleaf.cache=false
# %{변수A}을 쓰면 환경변수에 변수A가 있는지 확인해서 가져오고 없으면 기본값을 적용
# db정보 
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.jdbc-url=jdbc:mysql://${DB_URL:localhost}:3306/post?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true

# Windows 예시: C:/upload/  |  Linux 예시: /home/user/upload/
# 첨부파일 업로드할 위치 
# file.upload-dir=C:/upload/
file.upload-dir=/home/ubuntu/uploads

# 파일 업로드 용량 제한
spring.servlet.multipart.max-file-size=10MB
# 첨부파일 최대 3개 
spring.servlet.multipart.max-request-size=30MB
